"""Add translation_confidence field to reddit_comments

Revision ID: f18207ecb3c9
Revises: 1e58320c21b7
Create Date: 2025-09-05 20:49:35.371928

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f18207ecb3c9"
down_revision = "1e58320c21b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reddit_comments", "english_translation")
    op.drop_column("reddit_posts", "lgbtq_contexts_json")
    op.drop_column("reddit_posts", "lgbtq_relevance_score")
    op.drop_column("reddit_posts", "full_text")
    op.drop_column("reddit_posts", "contains_lgbtq_keywords")
    op.drop_column("reddit_posts", "lgbtq_keyword_count")
    op.drop_column("reddit_posts", "lgbtq_context")
    op.drop_column("reddit_posts", "english_translation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reddit_posts",
        sa.Column("english_translation", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "reddit_posts",
        sa.Column(
            "lgbtq_context", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "reddit_posts",
        sa.Column(
            "lgbtq_keyword_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "reddit_posts",
        sa.Column(
            "contains_lgbtq_keywords", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "reddit_posts",
        sa.Column("full_text", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "reddit_posts",
        sa.Column(
            "lgbtq_relevance_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "reddit_posts",
        sa.Column("lgbtq_contexts_json", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "reddit_comments",
        sa.Column("english_translation", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
