"""schema_enhancements_for_grant_deliverables

Revision ID: fac8e0a0d167
Revises: 1b7b496c6b13
Create Date: 2025-08-30 23:53:28.421313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac8e0a0d167'
down_revision = '1b7b496c6b13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
