"""add full_text field to reddit_posts

Revision ID: c54398d55c37
Revises: 644a6b681dff
Create Date: 2025-09-02 04:21:43.833076

"""



# revision identifiers, used by Alembic.
revision = "c54398d55c37"
down_revision = "644a6b681dff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
