"""Add missing columns for health and LGBTQ+ classification

Revision ID: 1e58320c21b7
Revises: a6da6b6a31aa
Create Date: 2025-09-04 15:13:38.639883

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = "1e58320c21b7"
down_revision = "a6da6b6a31aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reddit_posts", sa.Column("english_translation", sa.Text(), nullable=True)
    )
    op.add_column("reddit_posts", sa.Column("full_text", sa.Text(), nullable=True))
    op.add_column(
        "reddit_posts",
        sa.Column("contains_lgbtq_keywords", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "reddit_posts", sa.Column("lgbtq_keyword_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "reddit_posts", sa.Column("lgbtq_context", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "reddit_posts", sa.Column("lgbtq_contexts_json", sa.Text(), nullable=True)
    )
    op.add_column(
        "reddit_posts", sa.Column("lgbtq_relevance_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "reddit_comments", sa.Column("english_translation", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reddit_comments", "english_translation")
    op.drop_column("reddit_posts", "lgbtq_relevance_score")
    op.drop_column("reddit_posts", "lgbtq_contexts_json")
    op.drop_column("reddit_posts", "lgbtq_context")
    op.drop_column("reddit_posts", "lgbtq_keyword_count")
    op.drop_column("reddit_posts", "contains_lgbtq_keywords")
    op.drop_column("reddit_posts", "full_text")
    op.drop_column("reddit_posts", "english_translation")
    # ### end Alembic commands ###
