"""Initial schema with pgvector support

Revision ID: 8f8931975b65
Revises: c54398d55c37
Create Date: 2025-09-02 05:44:55.159323

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f8931975b65"
down_revision = "c54398d55c37"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reddit_comments", "english_translation")
    op.drop_column("reddit_posts", "full_text")
    op.drop_column("reddit_posts", "english_translation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reddit_posts",
        sa.Column("english_translation", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "reddit_posts",
        sa.Column("full_text", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "reddit_comments",
        sa.Column("english_translation", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
