"""Restore missing translation and analysis fields

Revision ID: 6945748703b9
Revises: f18207ecb3c9
Create Date: 2025-09-05 20:50:21.136093

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6945748703b9"
down_revision = "f18207ecb3c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
