"""Initial database schema with pgvector support

Revision ID: 1b7b496c6b13
Revises:
Create Date: 2025-08-30 19:23:12.173069

"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision = "1b7b496c6b13"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "misinformation_clusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_name", sa.String(length=200), nullable=True),
        sa.Column("cluster_description", sa.Text(), nullable=True),
        sa.Column(
            "centroid_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("post_count", sa.Integer(), nullable=True),
        sa.Column("avg_engagement", sa.Float(), nullable=True),
        sa.Column("primary_language", sa.String(length=10), nullable=True),
        sa.Column("subreddit_distribution", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "network_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_date", sa.DateTime(), nullable=True),
        sa.Column("num_nodes", sa.Integer(), nullable=True),
        sa.Column("num_edges", sa.Integer(), nullable=True),
        sa.Column("density", sa.Float(), nullable=True),
        sa.Column("num_communities", sa.Integer(), nullable=True),
        sa.Column("largest_community_size", sa.Integer(), nullable=True),
        sa.Column("avg_clustering_coefficient", sa.Float(), nullable=True),
        sa.Column("diameter", sa.Integer(), nullable=True),
        sa.Column("assortativity", sa.Float(), nullable=True),
        sa.Column("misinformation_centrality_correlation", sa.Float(), nullable=True),
        sa.Column("information_flow_speed", sa.Float(), nullable=True),
        sa.Column("metrics_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reddit_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.String(length=50), nullable=False),
        sa.Column("subreddit", sa.String(length=100), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("selftext", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("created_utc", sa.DateTime(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("upvote_ratio", sa.Float(), nullable=True),
        sa.Column("num_comments", sa.Integer(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("is_newcomer_related", sa.Boolean(), nullable=True),
        sa.Column(
            "title_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column(
            "content_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384),
            nullable=True,
        ),
        sa.Column(
            "combined_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384),
            nullable=True,
        ),
        sa.Column("misinformation_score", sa.Float(), nullable=True),
        sa.Column("contains_health_keywords", sa.Boolean(), nullable=True),
        sa.Column("keyword_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id"),
    )
    op.create_table(
        "user_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("annotator", sa.String(length=100), nullable=False),
        sa.Column("total_annotations", sa.Integer(), nullable=True),
        sa.Column("accuracy_score", sa.Float(), nullable=True),
        sa.Column("last_active", sa.DateTime(), nullable=True),
        sa.Column("achievements", sa.Text(), nullable=True),
        sa.Column("agreement_with_consensus", sa.Float(), nullable=True),
        sa.Column("expertise_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("annotator"),
    )
    op.create_table(
        "cluster_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.String(length=50), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("distance_to_centroid", sa.Float(), nullable=True),
        sa.Column("membership_confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["misinformation_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["reddit_posts.post_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post_annotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.String(length=50), nullable=True),
        sa.Column("annotator", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("is_consensus", sa.Boolean(), nullable=True),
        sa.Column("agreement_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["reddit_posts.post_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reddit_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.String(length=50), nullable=False),
        sa.Column("post_id", sa.String(length=50), nullable=True),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("created_utc", sa.DateTime(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.String(length=50), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("is_newcomer_related", sa.Boolean(), nullable=True),
        sa.Column(
            "content_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384),
            nullable=True,
        ),
        sa.Column("misinformation_score", sa.Float(), nullable=True),
        sa.Column("contains_health_keywords", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["reddit_posts.post_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment_id"),
    )
    op.create_table(
        "similar_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_post_id", sa.String(length=50), nullable=True),
        sa.Column("target_post_id", sa.String(length=50), nullable=True),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.Column("similarity_type", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_post_id"],
            ["reddit_posts.post_id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_post_id"],
            ["reddit_posts.post_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("similar_content")
    op.drop_table("reddit_comments")
    op.drop_table("post_annotations")
    op.drop_table("cluster_memberships")
    op.drop_table("user_stats")
    op.drop_table("reddit_posts")
    op.drop_table("network_metrics")
    op.drop_table("misinformation_clusters")
    # ### end Alembic commands ###
